name: CI

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - name: Install rustfmt
        run: rustup component add rustfmt
      - run: cargo fmt -- --check

  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - name: Install clippy
        run: rustup component add clippy
      - run: cargo clippy -- --deny warnings

  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - run: cargo test
